/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import { customInstance } from '../../custom-instance';
import type { ErrorType } from '../../custom-instance';



export const getHello = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<string>(
      {url: `/api/hello`, method: 'POST', signal
    },
      );
    }
  


export const getGetHelloMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getHello>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getHello>>, TError,void, TContext> => {
    
const mutationKey = ['getHello'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getHello>>, void> = () => {
          

          return  getHello()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetHelloMutationResult = NonNullable<Awaited<ReturnType<typeof getHello>>>
    
    export type GetHelloMutationError = ErrorType<unknown>

    export const useGetHello = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getHello>>, TError,void, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof getHello>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getGetHelloMutationOptions(options);

      return useMutation(mutationOptions);
    }
    