/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  StatisticDto
} from '../../models'
import { customInstance } from '../../custom-instance';
import type { ErrorType } from '../../custom-instance';



export const getStatistic = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<StatisticDto>(
      {url: `/api/statistic`, method: 'GET', signal
    },
      );
    }
  

export const getGetStatisticQueryKey = () => {
    return [`/api/statistic`] as const;
    }

    
export const getGetStatisticInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getStatistic>>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStatistic>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatisticQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatistic>>> = ({ signal }) => getStatistic(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStatistic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatisticInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getStatistic>>>
export type GetStatisticInfiniteQueryError = ErrorType<unknown>


export function useGetStatisticInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStatistic>>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStatistic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatistic>>,
          TError,
          Awaited<ReturnType<typeof getStatistic>>
        > , 'initialData'
      >, }

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatisticInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStatistic>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStatistic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatistic>>,
          TError,
          Awaited<ReturnType<typeof getStatistic>>
        > , 'initialData'
      >, }

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatisticInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStatistic>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStatistic>>, TError, TData>>, }

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetStatisticInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStatistic>>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStatistic>>, TError, TData>>, }

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatisticInfiniteQueryOptions(options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetStatisticQueryOptions = <TData = Awaited<ReturnType<typeof getStatistic>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatistic>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatisticQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatistic>>> = ({ signal }) => getStatistic(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStatistic>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatisticQueryResult = NonNullable<Awaited<ReturnType<typeof getStatistic>>>
export type GetStatisticQueryError = ErrorType<unknown>


export function useGetStatistic<TData = Awaited<ReturnType<typeof getStatistic>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatistic>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatistic>>,
          TError,
          Awaited<ReturnType<typeof getStatistic>>
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatistic<TData = Awaited<ReturnType<typeof getStatistic>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatistic>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatistic>>,
          TError,
          Awaited<ReturnType<typeof getStatistic>>
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatistic<TData = Awaited<ReturnType<typeof getStatistic>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatistic>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetStatistic<TData = Awaited<ReturnType<typeof getStatistic>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatistic>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatisticQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



