/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */

export interface AccessTokenDto {
  /** The access token */
  access_token: string;
}
