/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */
import type { ChallengeDtoDifficulty } from './challengeDtoDifficulty';
import type { TestCaseDto } from './testCaseDto';

export interface ChallengeDto {
  id: string;
  title: string;
  description: string;
  difficulty: ChallengeDtoDifficulty;
  starterCode: string;
  testCases: TestCaseDto[];
}
