/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */

export type ChallengeDtoDifficulty = typeof ChallengeDtoDifficulty[keyof typeof ChallengeDtoDifficulty];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChallengeDtoDifficulty = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD',
} as const;
