/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */
import type { GameDtoStatus } from './gameDtoStatus';
import type { GameParticipantDto } from './gameParticipantDto';

export interface GameDto {
  id: string;
  status: GameDtoStatus;
  participants: GameParticipantDto[];
}
