/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */

export type GameParticipantDtoLanguage = typeof GameParticipantDtoLanguage[keyof typeof GameParticipantDtoLanguage];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GameParticipantDtoLanguage = {
  JAVASCRIPT: 'JAVASCRIPT',
  TYPESCRIPT: 'TYPESCRIPT',
  PYTHON: 'PYTHON',
  JAVA: 'JAVA',
  CSHARP: 'CSHARP',
} as const;
