/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */

export interface GameDifficultyDto {
  /** The difficulty level of the game */
  difficulty: string;
  /** The number of games played at this difficulty level */
  count: number;
}
