/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */

export type GameDtoStatus = typeof GameDtoStatus[keyof typeof GameDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GameDtoStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
