/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */
import type { GameDifficultyDto } from './gameDifficultyDto';

export interface StatisticDto {
  /** Total number of games the user has participated in */
  totalGames: number;
  /** Number of games the user has completed */
  completedGames: number;
  /** Completion rate as a percentage string */
  completionRate: string;
  /** Number of games played by difficulty level */
  gamesByDifficulty: GameDifficultyDto[];
  /** Record of programming languages used and their frequency */
  languageUsage: string[];
  /** Average time taken to complete games in milliseconds */
  averageCompletionTimeMs: number;
  /** User's preferred programming language */
  preferredLanguage: string;
}
