/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionDtoStatus } from './subscriptionDtoStatus';

export interface SubscriptionDto {
  id: string;
  name: string;
  price: number;
  priceId: string;
  status: SubscriptionDtoStatus;
}
