/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */

export type SubscriptionDtoStatus = typeof SubscriptionDtoStatus[keyof typeof SubscriptionDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionDtoStatus = {
  active: 'active',
  available: 'available',
  canceled: 'canceled',
  incomplete: 'incomplete',
  incomplete_expired: 'incomplete_expired',
  past_due: 'past_due',
  paused: 'paused',
  trialing: 'trialing',
  unpaid: 'unpaid',
} as const;
