/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */
import type { TestCaseDtoInputs } from './testCaseDtoInputs';

export interface TestCaseDto {
  id: number;
  description: string;
  inputs: TestCaseDtoInputs;
  expectedOutput: string;
  hidden: boolean;
}
