/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionDto } from './subscriptionDto';

/**
 * The subscription of the user
 * @nullable
 */
export type UserDtoSubscription = SubscriptionDto | null;
