/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Code Dual API
 * The Code Dual API description
 * OpenAPI spec version: 1.0
 */

export interface UserDto {
  /** The ID of the user */
  id: string;
  /** The username of the user */
  username: string;
  /** The email of the user */
  email: string;
}
